# Generated by Django 5.1.4 on 2025-08-17 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('max_downloads', models.PositiveIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_share_links', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploadedfile')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.folder')),
            ],
            options={
                'indexes': [models.Index(fields=['share_id'], name='resource_sh_share_i_944a74_idx'), models.Index(fields=['created_by', 'created_at'], name='resource_sh_created_6bb01e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('file__isnull', False), ('folder__isnull', False), _connector='OR'), name='sharelink_has_file_or_folder')],
            },
        ),
    ]
