# Generated by Django 5.1.4 on 2025-09-11 15:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(help_text='System Admin who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Group Admin')], default='MEMBER', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, help_text='User who added this member to the group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_memberships', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='resource.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='user_groups', through='resource.GroupMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('shared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('share_type', models.CharField(choices=[('FILE', 'File'), ('FOLDER', 'Folder')], max_length=10)),
                ('can_download', models.BooleanField(default=True)),
                ('can_reshare', models.BooleanField(default=False)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.uploadedfile')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource.folder')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_items', to='resource.group')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_shares_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'user'], name='resource_gr_group_i_08ff7d_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'role'], name='resource_gr_user_id_562e2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('group', 'user')},
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name'], name='resource_gr_name_576581_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='resource_gr_created_f10fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsharing',
            index=models.Index(fields=['group', 'shared_at'], name='resource_gr_group_i_87e0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='groupsharing',
            index=models.Index(fields=['shared_by', 'shared_at'], name='resource_gr_shared__090fb1_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupsharing',
            constraint=models.UniqueConstraint(fields=('file', 'group'), name='unique_group_file_share'),
        ),
        migrations.AddConstraint(
            model_name='groupsharing',
            constraint=models.UniqueConstraint(fields=('folder', 'group'), name='unique_group_folder_share'),
        ),
        migrations.AddConstraint(
            model_name='groupsharing',
            constraint=models.CheckConstraint(condition=models.Q(('file__isnull', False), ('folder__isnull', False), _connector='OR'), name='groupsharing_has_file_or_folder'),
        ),
    ]
