# Generated by Django 5.1.4 on 2025-12-16 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_system_configuration_security'),
        ('resource', '0009_add_archive_metadata'),
    ]

    operations = [
    ]
