services:
  django:
    container_name: django
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - django_node_modules:/app/node_modules
    networks:
      - rc_network
    env_file:
      - ./backend/.env
    depends_on:
      - keycloak
    # Support large file uploads
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - ./frontend:/app
      - react_node_modules:/app/node_modules
    networks:
      - rc_network
    env_file:
      - ./frontend/.env
    depends_on:
      - django
    environment:
      - WATCHPACK_POLLING=true

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data   
    networks:
      - rc_network

  onlyoffice:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice
    ports:
      - "8081:80"
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=a4f8b9c331d7c4e5c9012fd993bb2aead4f187cb52efcbf3dd8970c19e7c2f5a
      - JWT_HEADER=Authorization
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_logs:/var/log/onlyoffice
    networks:
      - rc_network
    restart: unless-stopped

volumes:
  keycloak_data:
  django_node_modules:
  react_node_modules:
  onlyoffice_data:
  onlyoffice_logs:

networks:
  rc_network:
    driver: bridge



