# Generated by Django 5.1.4 on 2025-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_uploadedfile_is_archived_uploadedfile_is_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_starred',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
