# Generated by Django 5.1.4 on 2025-05-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_remove_uploadedfile_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesharing',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
