# Generated by Django 5.1.4 on 2025-05-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0014_filesharing_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='meta_tags',
            field=models.ManyToManyField(blank=True, related_name='files', to='resource.tag'),
        ),
    ]
